### ISSUE TITLE
Unsupported operand type on macOS (Python 3.9.6)

### ISSUE THREAD

**Issue by absynth42** [isotopp/subscribodil#2]
(mvenv) cku@MacBook-Pro subscribodil % python3 subscribodil.py --help

/Users/cku/workspace/subscribodil/mvenv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/cku/workspace/subscribodil/subscribodil.py", line 48, in <module>
    def follow(mastodon: Mastodon, account: AttribAccessDict) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
(mvenv) cku@MacBook-Pro subscribodil % python3 --version
Python 3.9.6

**Comment by isotopp** [comment]
Fixed in a37ca41c18fa9efb6cef67f497f2456c1af046e5.

You are using the macOS system python, 3.9.6, which does not understand `str | None` as a type (added in 3.10). I have reverted the syntax for `str | None` to `from typing import Optional` and `Optional[str]` and that should make it work.

Nonetheless I recommend installation of Homebrew from `brew.sh`, then use `brew doctor` to check the system

Apple is on a crusade against the GPL in their system. That is also why their system Python is being build with weird versions of weird SSL libraries. `brew install openssl` should fix that, and you will get a Python with OpenSSL then, this will hurt a lot less. Use `brew install python@3.12` to get a current Python.
